### ISSUE TITLE
Typos in the Synopsis

### ISSUE THREAD

**Issue by ronsavage** [ikenox/perl-enum#1]
(1) 
ORANGE => { name => 'Cherry', color => 'red' }, probably means
ORANGE => { name => 'Orange', color => 'red' },

(2)
Day->Sun->to_string;    # 'APPLE' probably means
Day->Sun->to_string;    # 'SUN'

**Comment by ikenox** [comment]
@ronsavage 
Thank you for your report!
I fixed it by pull request #2 .
